---
  - name: Discovery play
    hosts: web_servers
    gather_facts: true
    tasks:
      - name: Finding uptime
        ansible.builtin.shell: "uptime"
        register: up_time
      - name: Displaying Discovery info
        ansible.builtin.debug:
          msg: "{{inventory_hostname}},{{ansible_os_family}},{{ansible_system}},{{ansible_distribution}},{{up_time.stdout.split(',')[0].split('up')[-1]}}"
      - name: Removing old Discovery.csv file
        ansible.builtin.file:
          dest: ./Discovery.csv
          state: absent
        delegate_to: localhost
        run_once: ture
      - name: Creating Discovery.csv  file  with header
        ansible.builtin.copy:
          dest: ./Discovery.csv
          content: "Server_Name, OS Family, OS Name, OS Distribution, uptime\n"
        delegate_to: localhost
        run_once: true
      - name: UPdating info of each server in csv file
        ansible.builtin.lineinfile:
          path: ./Discovery.csv
          line: "{{inventory_hostname}},{{ansible_os_family}},{{ansible_system}},{{ansible_distribution}},{{up_time.stdout.split(',')[0].split('up')[-1]}}"
        delegate_to: localhost 

      - name: Take out of load balancer pool
        local_action: ansible.builtin.command /usr/bin/take_out_of_pool {{ inventory_hostname }}