---
 -  name: Error handling
    hosts: all
    gather_facts: false
    tasks:
    #  - ansible.builtin.command: "ls /home"
    #    register: out
    #    failed_when: out.rc==0
    #  - debug: var=out
      - ansible.builtin.command: "ls /home"
        register: out
      - fail:
          msg: "Failed because rc is 0"
        when: out.rc==0