---
  - name: Simple play to install multiple pkgs
    hosts: web_servers
    gather_facts: true
    become: yes
    tasks:
      - ansible.builtin.include_tasks: install_webserver_{{ansible_os_family}}.yml
      - ansible.builtin.include_tasks: install_java_{{ansible_os_family}}.yml