---
  - name: Play with 5 tasks
    hosts: localhost
    gather_facts: false
    tasks:
      - ansible.builtin.debug:
          msg: "This is a first task"
        tags:
          - first
          - common
          - always
      - ansible.builtin.debug:
          msg: "This is a second task"
        tags:
          - second
          - never
      - ansible.builtin.debug:
          msg: "This is a third task"
        tags:
          - third
          - common
          - never
      - ansible.builtin.debug:
          msg: "This is a fourth task"
        tags:
          - fourth
          - never
      - ansible.builtin.debug:
          msg: "This is a fifth task"
        tags:
          - fifth
          - never
